apiVersion: apps/v1
kind: Deployment
metadata:
  name: airport-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airport-service
  template:
    metadata:
      labels:
        app: airport-service
    spec:
      containers:
      - name: airport-service
        image: siddb/airport-service:v1.0.0 # Your image name
        ports:
        - containerPort: 3002
        envFrom:
        - secretRef:
            name: airport-service-secret