apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
      - name: flight-service
        image: siddb/flight-service:v1.0.1 # Your new image name
        ports:
        - containerPort: 3004
        envFrom:
        - secretRef:
            name: flight-service-secret