# 1. Persistent Volume Claim: A request for storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage

---
# 2. Deployment: How to run the PostgreSQL container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        # These credentials must match what airport-service expects
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "airports_db"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # Mount the persistent volume here
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc # Use the PVC we defined above

---
# 3. Service: The stable network address for the database
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc # This name MUST match the host in the DATABASE_URL
spec:
  selector:
    app: postgres # Find pods with this label
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Only accessible inside the cluster