apiVersion: v1
kind: Service
metadata:
  name: live-tracking-service-svc
spec:
  selector:
    app: live-tracking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3007
  type: ClusterIP