apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2 # Run 2 instances for high availability
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: siddb/user-service:v1.0.7
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: user-service-secret