apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80 # The port the service will be available on
      targetPort: 3001 # The port on the container
  type: ClusterIP # Only exposes the service inside the cluster